#!/usr/local/bin/perl -s

use strict;
use warnings;

use FlatFile::DataStore::Utils;

our( $from_dir, $from_name, $to_dir, $to_name, $to_uri, $nohist );

die "usage: $0 -from_dir=/from/dir -from_name=ds1 -to_dir=/to/dir -to_name=ds2 -to_uri=uri2\n"
    unless $from_dir and $from_name and $to_dir and $to_name;

#---------------------------------------------------------------------
# main

FlatFile::DataStore::Utils::validate( $from_dir, $from_name                             );
if( $nohist ) {
FlatFile::DataStore::Utils::migrate_nohist ( $from_dir, $from_name, $to_dir, $to_name, $to_uri );
}
else {
FlatFile::DataStore::Utils::migrate ( $from_dir, $from_name, $to_dir, $to_name, $to_uri );
}
FlatFile::DataStore::Utils::validate(                        $to_dir, $to_name          );
FlatFile::DataStore::Utils::compare ( $from_dir, $from_name, $to_dir, $to_name          );

__END__
